# Generated by Django 5.1.2 on 2024-10-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='A brief description of the product (max 100 characters)', max_length=100),
        ),
    ]
