# Generated by Django 5.1.1 on 2024-09-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_number',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
