# Generated by Django 5.1.1 on 2024-09-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_alter_purchaseorder_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('UNSUCCESSFUL', 'Unsuccessful')], default='PENDING', max_length=20),
        ),
    ]
