# Generated by Django 5.1.1 on 2024-09-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_shippinglocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinglocation',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
