# Generated by Django 5.1.1 on 2024-09-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_shippinglocation_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
