# Generated by Django 5.1.1 on 2024-09-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_alter_cart_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('last_sequence', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
